name: Contracts

on:
  pull_request:
    paths:
      - "app/**/*.rb"
      - "config/**/*.rb"
      - "platform/contracts/**"

jobs:
  contracts:
    uses: LMafra/platform-event-mesh/platform/ci/workflows/contracts.yaml@main
    with:
      working-directory: pickup-game-manager
      install-command: bundle install
      test-command: bundle exec rspec spec/jobs/events/publish_payment_received_job_spec.rb
      schema-glob: platform/contracts/schemas/finance/payment.received.v1.json
