name: Contracts

on:
  pull_request:
    paths:
      - "app/**/*.rb"
      - "config/**/*.rb"
      - "platform/contracts/**"

jobs:
  contracts:
    uses: SarradaHub/platform/.github/workflows/contracts.yaml@main
    with:
      working-directory: saturday_league_football
      install-command: bundle install
      test-command: bundle exec rspec spec/jobs/events/publish_match_scheduled_job_spec.rb
      schema-glob: platform/contracts/schemas/scheduling/*.json

